---

- name: Send vRA Request
  uri:
    url: "https://{{ vra_host }}/catalog-service/api/consumer/entitledCatalogItems/{{ blueprint_id }}/requests"
    method: POST
    follow_redirects: all
    headers:
      Accept: "application/json"
      Authorization: "{{ authorization }}"
    validate_certs: no
    body: "{{ blueprint_template }}"
    return_content: yes
    body_format: json
    timeout: 120
    status_code: 201
  register: request_result

- debug:
    var: request_result

- set_fact:
    request_location: "{{ request_result.location }}"

- debug:
    var: request_location
