stages:
  - build
  - test
  - deploy
  - clean

Deployment:
  stage: build
  script:
    - ansible-playbook playbooks/deployment_create.yml --extra-vars="blueprint_name=Linux"

Ping:
  stage: test
  script:
    - export IP_ADDRESS=`cat /tmp/ip_address`
    - ansible-playbook playbooks/test_ping.yml --extra-vars="ip_address=$IP_ADDRESS"

Decomission:
  stage: clean
  script:
    - export DEPLOYMENT_ID=`cat /tmp/deployment_id`
    - ansible-playbook playbooks/deployment_action.yml --extra-vars="deployment_id=$DEPLOYMENT_ID action_name=Destroy"
