---
- hosts: localhost
  connection: local

  vars:
    vra_host: vra.vlab.local
    vra_username: ehc_sysadmin
    vra_password: Password123!
    vra_tenant: prod
    debug: true
    blueprint_id: abf93246-a9fc-42e9-ae3c-ad9951ab9626
    destroy_id: 5a587276-6ea7-4d4e-aa2d-a2fe5c6d36ce

  tasks:
   - include_tasks: token/get.yml
   - include_tasks: blueprint/get.yml
   - include_tasks: template/get.yml
   - include_tasks: request/submit.yml
   - include_tasks: request/status.yml
   - include_tasks: detail/get.yml
   - include_tasks: tests/ping.yml
   - include_tasks: actions/get.yml
   - include_tasks: destroy/get_template.yml
   - include_tasks: destroy/destroy_vm.yml
   - include_tasks: destroy/status.yml
