---

- set_fact:
    my_template: "{{ blueprints.json }}"

- dict_modify:
    parent: data
    key: memory
    value: 2048
    json: "{{ my_template }}"
  register: my_template

- dict_modify:
    parent: data
    key: cpu
    value: 2
    json: "{{ my_template }}"
  register: my_template

- debug:
    var: my_template

- set_fact:
    blueprint_template: "{{ my_template.json.json }}"
  when: my_template.changed

- set_fact:
    blueprint_template: "{{ my_template }}"
  when: my_template.changed == False