---
- name: Destroy VM
  uri:
    url: "https://{{ vra_host }}/catalog-service/api/consumer/resources/{{ deployment_id }}/actions/{{ destroy_id }}/requests"
    method: POST
    follow_redirects: all
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
      Authorization: "{{ authorization }}"
    validate_certs: no
    body: "{{ destroy.json }}"
    body_format: json
    timeout: 120
    status_code: 201
  register: destroy_vm

- debug:
    var: destroy_vm

- set_fact:
    destroy_location: "{{ destroy_vm.location }}"