---
- hosts: localhost
  connection: local

  vars:
    vra_host: vra.vlab.local
    vra_username: ehc_sysadmin
    vra_password: Password123!
    vra_tenant: prod
    debug: false
    blueprint_name: Linux

  tasks:
  # Get Token
  - include_tasks: tasks/token/get.yml

  # Get Blueprint
  - include_tasks: tasks/blueprint/get.yml
  - include_tasks: tasks/blueprint/filter.yml
  - include_tasks: tasks/template/get.yml

  # Submit Request
  - include_tasks: tasks/request/submit.yml
  - include_tasks: tasks/request/status.yml
    vars:
      delay: 35
      retries: 20

  # Get Details
  - include_tasks: tasks/detail/get.yml

  # Run Tests
  - include_tasks: tasks/tests/ping.yml

  ########################################################

  # Get Actions
  - include_tasks: tasks/actions/get.yml
    vars:
      my_resource: "{{deployment_id}}"
  - include_tasks: tasks/actions/filter.yml
    vars:
      my_action: "Destroy"
  # Remove Deployment
  - include_tasks: tasks/destroy/get_template.yml
    vars:
      my_resource: "{{deployment_id}}"
  - include_tasks: tasks/destroy/destroy_vm.yml
    vars:
      my_resource: "{{deployment_id}}"
  - include_tasks: tasks/destroy/status.yml
