---
- hosts: localhost
  connection: local

  vars:
    vra_host: vra.vlab.local
    vra_username: ehc_sysadmin
    vra_password: Password123!
    vra_tenant: prod
    debug: false
    blueprint_name: Linux
    action_name: Destroy

  tasks:
  # Get Token
  - include_tasks: tasks/token/get.yml

  # Get Actions
  - include_tasks: tasks/actions/get.yml
    vars:
      my_resource: "{{ deployment_id }}"

  - include_tasks: tasks/actions/filter.yml
    vars:
      my_action: "{{ action_name }}"

  # Remove Deployment
  - include_tasks: tasks/actions/get_template.yml
    vars:
      my_resource: "{{ deployment_id }}"

  - include_tasks: tasks/actions/request.yml
    vars:
      my_resource: "{{ deployment_id }}"

  - include_tasks: tasks/actions/status.yml

  # Clean Details
  - include_tasks: tasks/detail/clean.yml