---
- hosts: localhost
  connection: local

  vars:
    vra_host: vra.vlab.local
    vra_username: ehc_sysadmin
    vra_password: Password123!
    vra_tenant: prod
    debug: false
    blueprint_name: Linux

  tasks:
  # Run Tests
  - include_tasks: tasks/tests/ping.yml
