---
- hosts: localhost
  connection: local

  vars:
    vra_host: vra.vlab.local
    vra_username: ehc_sysadmin
    vra_password: Password123!
    vra_tenant: prod
    debug: false
    blueprint_name: Linux

  tasks:
  # Get Token
  - include_tasks: tasks/token/get.yml

  # Get Actions
  - include_tasks: tasks/actions/get.yml
    vars:
      my_resource: "{{resource_id}}"
  - include_tasks: tasks/actions/filter.yml
  # Remove VM
  - include_tasks: tasks/destroy/get_template.yml
    vars:
      my_resource: "{{resource_id}}"
  - include_tasks: tasks/destroy/destroy_vm.yml
    vars:
      my_resource: "{{resource_id}}"
  - include_tasks: tasks/destroy/status.yml